---
#
# Ansible managed
#
repository:
  description: Install and configure minikube on your system.
  homepage: https://robertdebock.nl/
  topics: minikube, development, ansible, molecule, tox, playbook
