---
roles:
  - name: robertdebock.bootstrap
  - name: robertdebock.core_dependencies
  - name: robertdebock.docker
  - name: robertdebock.epel
  - name: robertdebock.kubectl
  - name: robertdebock.python_pip
  - name: robertdebock.service
  - name: robertdebock.sysctl
  - name: robertdebock.users
collections:
  - name: ansible.posix
  - name: community.general
